# Generated by Django 5.0 on 2023-12-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('achievement', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cricket',
                'managed': False,
            },
        ),
    ]
