# Generated by Django 5.0 on 2023-12-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronin', '0003_kabadi_delete_cricket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kabadi',
            table='kabadi',
        ),
    ]
