# Generated by Django 5.0 on 2023-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronin', '0004_alter_kabadi_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('achievement', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cricket',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='kabadi',
        ),
    ]
