# Generated by Django 5.0 on 2024-01-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronin', '0006_kabadi_alter_cricket_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kabadi',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='cricket',
            table='cricket',
        ),
    ]
