# Generated by Django 5.0 on 2024-01-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronin', '0007_alter_kabadi_options_alter_cricket_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kabadi',
            table='kabadi',
        ),
    ]
